# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d239915521bd3aee74ae43bdccb22ee34cf52d690a0f0b466ede996cfbd50a26615889a0438cbad0fbde5ef6b1a6a44660225cd07872c75feee28bb03b2bca9

test:
  secret_key_base: 51e828588922a927934b3d219178a7faefbad011c8b05fedf84eb2dea3b63e2e7cafaeb8bc63d2f57753cd515df7311b168b53b4861de76c940c25bc400311fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
